version: "3.8"

services:
  app:
    build: .
    container_name: classing-container
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0
    container_name: mongodb-container
